### ISSUE TITLE
Correção - LAB-01

### ISSUE THREAD

**Issue by fsantanna-uerj** [EduardoArthur/LP1#1]
- colocar no formato pedido no enunciado
- um diretório por laboratório
- um exercício por arquivo
- imagens com a execução dos exercícios

**Comment by fsantanna-uerj** [comment]
Continua sem um diretório separado para o lab-01/

**Comment by EduardoArthur** [comment]
tudo certo agora?

**Comment by fsantanna** [comment]
Sim. Pode fechar essa issue.
