### ISSUE TITLE
Tem uma solução mais simples que não precisa desse contador `d`

### ISSUE THREAD

**Issue by fsantanna** [EduardoArthur/LP1#2]
https://github.com/EduardoArthur/LP1/blob/fe00beaf0edf82cbc8d035e88ddc8a523ad0e867/exercicios%20dos%20slides/primo.c#L4

**Comment by EduardoArthur** [comment]
retirei o contador

**Comment by fsantanna** [comment]
Agora está errado.
A função nunca retorna `1`?

**Comment by EduardoArthur** [comment]
ele retorna 0 informando que não é primo. caso a resposta não seja 0 é porque ele é primo

**Comment by fsantanna** [comment]
E onde você dá essa resposta diferente de 0?
Seria retornando 1 em algum lugar.
